version: 2.1

executors:
  docker-builder:
    docker:
      - image: meliuz/docker-builder:1.0.0
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

commands:
  docker-login:
    steps:
      - run:
          name: Log into Docker Hub
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}

jobs:
  lint:
    docker:
      - image: meliuz/docker-linter:1.2.0
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

    steps:
      - checkout

      - run:
          name: Lint project files
          command: |
            docker-entrypoint " \
              lint-commit origin/master && \
              lint-dockerfile && \
              lint-markdown && \
              lint-yaml"

  build:
    executor: docker-builder
    steps:
      - checkout
      - setup_remote_docker
      - docker-login

      - run:
          name: Build image
          command: |
            export APPLICATION_NAME=${CIRCLE_PROJECT_REPONAME}

            build-image meliuz/${CIRCLE_PROJECT_REPONAME}:testing . APPLICATION_NAME

      - run:
          name: Save image
          command: |
            mkdir -p cache

            if [ "${CIRCLE_TAG}" = "" ]; then
              circleci step halt
            fi

            docker save \
              -o cache/${CIRCLE_PROJECT_REPONAME}-${CIRCLE_TAG}.tar \
              meliuz/${CIRCLE_PROJECT_REPONAME}:testing

      - persist_to_workspace:
          root: cache
          paths:
            - "*.tar"

  push:
    executor: docker-builder
    steps:
      - setup_remote_docker

      - attach_workspace:
          at: cache

      - docker-login

      - run:
          name: Load saved image
          command: docker load -i cache/${CIRCLE_PROJECT_REPONAME}-${CIRCLE_TAG}.tar

      - run:
          name: Push image
          command: |
            IMAGE_NAME=meliuz/${CIRCLE_PROJECT_REPONAME}

            push-image ${IMAGE_NAME}:testing latest
            push-image ${IMAGE_NAME}:testing ${CIRCLE_TAG}

workflows:
  version: 2.1

  meliuz-workflow:
    jobs:
      - lint:
          context: global
          filters:
            branches:
              ignore: master
            tags:
              only: /.*/

      - build:
          context: global
          requires:
            - lint
          filters:
            branches:
              ignore: master
            tags:
              only: /.*/

      - push:
          context: global
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+){2}$/
